### ISSUE TITLE
Set canonical URL from same news on different list pages to same canonical URL?

### ISSUE THREAD

**Issue by mschmitz89** [georgringer/news_seo#10]
Hi! 

Is it possible to set the canonical URL automatically to the same URL when the news is output on different list pages?

Thank you very much! 🙏

**Comment by georgringer** [comment]
thanks for creating the issue. this is not that easy and would need some more work/thinking, e.g. where to persist which page is used for resolving it? could be in the site settings but what if there are multiple pages with multiple variants? that is not that easy but yes for sure solveable.

are you or your client interested in sponsoring this feature?

**Comment by mschmitz89** [comment]
Hello Georg, thank you for your answer!

Unfortunately, we had to do it quickly due to a lack of time, so we first reverted to the extension cs_seo and simply used the following TypoScript for the purpose.

Maybe this will help someone:

```
[traverse(request.getQueryParams(), 'tx_news_pi1/news') > 0] 
config.disableCanonical = 1
page.headerData.20 = TEXT
page.headerData.20 {
    wrap = <link rel="canonical" href="|">
    typolink {
      parameter = 1234
      returnLast = url
      forceAbsoluteUrl = 1
      additionalParams.data = tx_csseo_url_parameters
      useCacheHash = 1
    }
}
[end]
```

Unfortunately it overwrites the possibility of cs_seo to overwrite the parameter with the individually set canonical URL of the news, but for now it is sufficient for our purposes.

I'm sorry that I can't provide any other support at the moment.

Thanks and best regards

**Comment by georgringer** [comment]
hi @mschmitz89 if you got such a specific need it could have been solved by using another event
