### ISSUE TITLE
Compatibility with news ^11.0

### ISSUE THREAD

**Issue by thomasrawiel** [georgringer/news_seo#15]
I assume ext:news_seo is still needed to provide robots index/follow for news records.

Will this extension be updated for news ^11.0 / TYPO3 12?

```
"require": {
    "php": ">= 7.4 < 8.3",
    "georgringer/news": "^8.6 || ^9 || ^10",
    "typo3/cms-seo": "^10.4 || ^11.5 || ^12"
  },
```

Edit: I just saw the latest commits, I guess there's just a tag missing?

**Comment by georgringer** [comment]
tagged it, thanks! https://github.com/georgringer/news_seo/releases/tag/2.0.2
