### ISSUE TITLE
no canonical tag if noindex

### ISSUE THREAD

**Issue by georgringer** [georgringer/news_seo#2]
![image](https://user-images.githubusercontent.com/1905663/204286969-944f80bc-7106-48d9-8e7a-64cc7dd2793e.png)

I tested your news_seo and found the following:
TYPO3 10.4.32, news 9.4.0, news 10.0
news-seo dev-main branch
Pre-test changes:
For the sitemap.xml I added the new no_index field additionalWhere = AND no_index = 0
The following assumptions were taken for this test:
The metatags are not changed via typoscript or fluid metatag viewhelper
metatags or hreflang/canonical are not manipulated except in core, news or news_seo
Result:
The no_index and no_follow fields work as expected.
The canonical url is correctly generated, but should not be rendered when no_index=1.
The news_seo extension fields have no influence on the generation of the hreflang tags. The generation of the hreflang tags depends only on the no_index setting of the detail page

**Comment by thomasrawiel** [comment]
### Canonical Tag

- page no_index=1, News record no_index=1
The canonical is **not** rendered - correct

- page no_index=0, News record no_index=0
The canonical is rendered - correct

- page: no_index=0, News record no_index=1
The canonical is rendered - **not** correct

- page: no_index=1, News record no_index=0
The canonical is rendered - correct

The news record property no_index only has an effect on the canonical tag, when the page property no_index=1.
If the page property no_index=0 the canonical tag is always rendered.


### Robots Tag with max-image-preview:
Works as expected

Tested on [31b141f83dcf58e17a19bebbc5fb2f32fdeb900d](https://github.com/georgringer/news_seo/commit/31b141f83dcf58e17a19bebbc5fb2f32fdeb900d)

**Comment by thomasrawiel** [comment]
Hreflangs (tested with dev-main f8d1e21)

In TYPO3 10 the line `$this->cObj->setRequest($event->getRequest());` produces an exception 

> Call to undefined method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::setRequest()
> in /var/www/html/public/typo3conf/ext/news_seo/Classes/EventListener/ModifyHrefLangEventListener.php line 50
This function doesn't exist in TYPO3 10.
Also, not sure, if you need to set the request for this task.

Additionally, the hreflangs should not be rendered when, the news records' field no_index=1.

Proposed change:

```
$newsAvailabilityChecker = GeneralUtility::makeInstance(NewsAvailability::class);
$newsId = $newsAvailabilityChecker->getNewsIdFromRequest();

if ($newsId > 0) {
    if($this->isNoIndex($newsId)) {
        return;
    }

    if ((int)\TYPO3\CMS\Core\Utility\VersionNumberUtility::getNumericTypo3Version() > 10) {
        $this->cObj->setRequest($event->getRequest());
    }
    $languages = $this->languageMenuProcessor->process($this->cObj, [], [], []);
...
```

```
protected function isNoIndex(int $newsId): bool
{
  $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
      ->getQueryBuilderForTable('tx_news_domain_model_news');
  $row = $queryBuilder->select('uid', 'no_index')
      ->from('tx_news_domain_model_news')
      ->where(
          $queryBuilder->expr()->eq('uid', $queryBuilder->createNamedParameter($newsId, \PDO::PARAM_INT))
      )
      ->execute()
      ->fetch();

  return (bool)$row['no_index'];
}

```
Maybe add this in a Utility or Service class, duplicate would be in class GeorgRinger\NewsSeo\EventListener\ModifyUrlForCanonicalTagEventListener

**Comment by georgringer** [comment]
@thomasrawiel fixed it just now! thanks for your report

**Comment by thomasrawiel** [comment]
Thanks, just tested it on `0014ccde031bcb3b3c452b4f08c9d4dd0059fb81`

It works as expected, assuming that the page property no_index=1 on the detail page.

Thanks!
