### ISSUE TITLE
Call to undefined method NewsAvailability::getNewsIdFromRequest()

### ISSUE THREAD

**Issue by Tobias-Gl** [georgringer/news_seo#3]
We get the error "Oops, an error occurred!
Call to undefined method GeorgRinger\News\Seo\NewsAvailability::getNewsIdFromRequest()".

We use TYPO3 v. 10 with news 8.6.
The version called here is not present in news 8.6 and was implemented only with 9.1.

Call news_seo:
https://github.com/georgringer/news_seo/blob/0014ccde031bcb3b3c452b4f08c9d4dd0059fb81/Classes/EventListener/ModifyHrefLangEventListener.php#L49

Method in news 9.1:
https://github.com/georgringer/news/blob/9.1.0/Classes/Seo/NewsAvailability.php#L128

**Comment by georgringer** [comment]
thanks for the test, fixed with https://github.com/georgringer/news_seo/commit/4338c9f7114a401b8dd215268b0f63e98c9229f2
