### ISSUE TITLE
PHP 7 compatibility < 7.4 (typed properties)

### ISSUE THREAD

**Issue by thomasrawiel** [georgringer/news_seo#4]
Hi Georg, 

in php versions < 7.4 the typed class properties
```
protected TypoScriptFrontendController $typoScriptFrontendController;
protected PageRepository $pageRepository;
```
in class ModifyUrlForCanonicalTagEventListener
cause parse errors like
  syntax error, unexpected 'TypoScriptFrontendController' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

Please consider adding PHP 7.4 as a minimum requirement (^7.4 || ^8.0) or remove the property types

**Comment by georgringer** [comment]
Fixed with https://github.com/georgringer/news_seo/commit/4793cf0789f4892f8cafdc5b0d404e0479fa84b4
