### ISSUE TITLE
Add canonical field

### ISSUE THREAD

**Issue by ste101** [georgringer/news_seo#5]
It would be great to have the canonical field also.

**Comment by ursbraem** [comment]
@georgringer can we sponsor this feature?

**Comment by georgringer** [comment]
@ursbraem @ste101 wanna check out https://github.com/georgringer/news_seo/pull/6 or the branch `canonical` should work fine out of the box

**Comment by ursbraem** [comment]
Thanks Georg! My colleague @domibwagz will do it, might take a few days.

**Comment by ursbraem** [comment]
Currently, it seems to output the link to the page where the news is on:

![CleanShot 2022-12-23 at 17 27 49@2x](https://user-images.githubusercontent.com/1446443/209367877-733df556-c63e-425d-8c0b-0b1bb422037a.jpg)

The idea is that it outputs the link given in the "canonical" field.

**Comment by georgringer** [comment]
@ursbraem don't really understand the problem. currently for me (on v11):

<img width="524" alt="image" src="https://user-images.githubusercontent.com/1905663/209443665-ab3deb1c-bc3b-4b80-b09c-e5d4778dbc0b.png">
leads to 

<img width="722" alt="image" src="https://user-images.githubusercontent.com/1905663/209443689-e316112b-2abf-4e20-b1fc-9c5d46d1463c.png">

**Comment by ursbraem** [comment]
On v 10.4.34:

![CleanShot 2022-12-25 at 21 18 11@2x](https://user-images.githubusercontent.com/1446443/209481043-bdb4052a-ae8d-4599-b81c-44c2ae49b63c.jpg)

But in the frontend: 

![CleanShot 2022-12-25 at 21 21 39@2x](https://user-images.githubusercontent.com/1446443/209481062-145f4333-172e-4655-962a-f2e1abda4ce8.jpg)

**Comment by ste101** [comment]
Same here.
The news detail page has no_index=0 so line 42 in ModifyUrlForCanonicalTagEventListener.php is always true
```
if (!empty($href) || (int)$this->typoScriptFrontendController->page['no_index'] === 0) {
```

**Comment by ste101** [comment]
I think it should be possible to use no_index and canonical also:
https://www.searchenginejournal.com/when-to-use-rel-canonical-or-noindex-or-both/427522/

**Comment by georgringer** [comment]
I am still confused. should I change something, should it be configurable or everything fine ^^

**Comment by ursbraem** [comment]
On TYPO3 10 (where we tested) the URL rendered as canonical on the news page is wrong. 
Instead of  displaying the link added in the new canonical field, it outputs the link to the current news itself.

@ste101 says this is probably because of this [condition](https://github.com/georgringer/news_seo/blob/canonical/Classes/EventListener/ModifyUrlForCanonicalTagEventListener.php#L39). 

I would also say try instead:

        if (!empty($href) {
            return;
        }

**Comment by ursbraem** [comment]
Works with PR https://github.com/georgringer/news_seo/pulls
