### ISSUE TITLE
Contradictive setting name and label

### ISSUE THREAD

**Issue by ursbraem** [georgringer/news_seo#8]
![CleanShot 2022-12-29 at 13 53 03@2x](https://user-images.githubusercontent.com/1446443/209954280-30777cb5-69a1-40b7-aa14-c173d175c9cc.jpg)

**Comment by ursbraem** [comment]
Similar to these settings in the core's pages module: 

![CleanShot 2022-12-29 at 13 58 47@2x](https://user-images.githubusercontent.com/1446443/209954435-b782c293-d765-4dda-8bbf-860680718fe0.jpg)

... this has a contradictive Label and field name which can lead to confusions ("If you don't want robots to index your page, turn off the `no_index` field – that makes no sense) ". 

But unlike the core, the extension is young and this can be changed without major consequences. It's a breaking change though for existing users

My suggestion: 

* Use label "Don't index this article" and output robots tag attribute when `no_index` is turned **on**
* OR use Label "Index this article", but rename field to `index`, and output output robots tag attribute when `no_index` is turned **off**

**Comment by georgringer** [comment]
@ursbraem wanna test the branch `field-renaming` https://github.com/georgringer/news_seo/compare/field-renaming?expand=1?

**Comment by ursbraem** [comment]
I'll test

**Comment by ursbraem** [comment]
For new as well as existing articles, the robots fields now default to "off".

![Screenshot- 2023-01-09 at 15 48 39@2x](https://user-images.githubusercontent.com/1446443/211336270-dd2caaa2-e104-46ba-a84e-41436d5488dc.jpg)

This is undesired, they should be "on" unless something else is specified explicitly by the user

**Comment by georgringer** [comment]
@ursbraem please check latest commit

**Comment by ursbraem** [comment]
👍 Works! 
It's a checkbox now, not a toggle, but that is fine I think
